apiVersion: bitcoin.kiln-fired.github.io/v1alpha1
kind: LightningNode
metadata:
  name: lnd
spec:
  bitcoinConnection:
    nodeRef: btcd
  rpc:
    secretName: lnd-rpc
  wallet:
    password:
      secretName: alice-wallet
      secretKey: password
    seed:
      secretName: seed
      mnemonicKey: mnemonic
      passphraseKey: passphrase
